package com.example.Royal_Blueberry.controller;

import com.example.Royal_Blueberry.config.OpenApiConfig;
import com.example.Royal_Blueberry.dto.auth.*;
import com.example.Royal_Blueberry.security.CustomUserDetails;
import com.example.Royal_Blueberry.service.AuthService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/auth")
@RequiredArgsConstructor
@Tag(name = "Authentication", description = "Authentication and authorization endpoints")
public class AuthController {

    private final AuthService authService;

    @Operation(
            summary = "Get Google login URL",
            description = """
                    Returns a ready-to-open Google OAuth login URL generated by the backend.
                    FE does not need to know the Google client ID or configured redirect URI.
                    
                    The response also includes:
                    - `state`: send this back together with the authorization code
                    - `redirectUri`: the callback URI currently configured on the server
                    - `scope`: the Google scopes requested by the login flow
                    """,
            security = {})
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Google login URL generated"),
            @ApiResponse(responseCode = "500", description = "Google login is not configured")
    })
    @GetMapping("/google/url")
    public ResponseEntity<GoogleLoginUrlResponse> getGoogleLoginUrl() {
        return ResponseEntity.ok(authService.getGoogleLoginUrl());
    }


    @Operation(
            summary = "Login with email and password",
            description = """
                    Authenticate a user with local credentials.
                    Returns JWT access token and refresh token.
                    The WPF client should store these tokens securely
                    and send the access token in the Authorization header.
                    """,
            security = {})
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Login successful"),
            @ApiResponse(responseCode = "401", description = "Invalid credentials")
    })
    @PostMapping("/login")
    public ResponseEntity<AuthResponse> login(@Valid @RequestBody LoginRequest request) {
        AuthResponse response = this.authService.login(request);
        return ResponseEntity.ok(response);
    }


    @Operation(
            summary = "Register a new user",
            description = """
                    Create a new local user account.
                    Default role is USER. Returns JWT tokens upon successful registration.
                    """,
            security = {})
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Registration successful"),
            @ApiResponse(responseCode = "400", description = "Invalid input"),
            @ApiResponse(responseCode = "409", description = "Username or email already exists")
    })
    @PostMapping("/register")
    public ResponseEntity<AuthResponse> register(@Valid @RequestBody RegisterRequest request) {
        AuthResponse response = authService.register(request);
        return ResponseEntity.ok(response);
    }


    @Operation(
            summary = "Login with Google",
            description = """
                    Complete Google OAuth 2.0 login using the authorization code
                    returned by Google's redirect after opening the backend-provided login URL.
                    
                    The client should:
                    1. Call GET /api/auth/google/url
                    2. Open the returned `url` in a browser/WebView
                    3. Receive `code` and `state` on the callback
                    4. Send `code` and `state` to this endpoint
                    
                    The backend exchanges the authorization code with Google
                    using the configured client ID, client secret, and redirect URI.
                    
                    If the user doesn't exist, a new account is created automatically.
                    """,
            security = {})
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Google login successful"),
            @ApiResponse(responseCode = "401", description = "Invalid Google authorization code or state"),
            @ApiResponse(responseCode = "409",
                    description = "Email already registered with local account")
    })
    @PostMapping("/google")
    public ResponseEntity<AuthResponse> loginWithGoogle(
            @Valid @RequestBody GoogleLoginRequest request) {
        AuthResponse response = authService.loginWithGoogle(request);
        return ResponseEntity.ok(response);
    }


    @Operation(
            summary = "Refresh access token",
            description = """
                    Use a valid refresh token to obtain a new access token.
                    Call this when the access token expires (HTTP 401).
                    The refresh token remains the same.
                    """,
            security = {})
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Token refreshed successfully"),
            @ApiResponse(responseCode = "401", description = "Invalid or expired refresh token")
    })
    @PostMapping("/refresh-token")
    public ResponseEntity<AuthResponse> refreshToken(
            @Valid @RequestBody RefreshTokenRequest request) {
        AuthResponse response = authService.refreshToken(request);
        return ResponseEntity.ok(response);
    }


    @Operation(
            summary = "Get current authenticated user",
            description = "Returns the profile of the currently authenticated user.",
            security = @SecurityRequirement(name = OpenApiConfig.SECURITY_SCHEME_NAME))
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "User info returned"),
            @ApiResponse(responseCode = "401", description = "Not authenticated")
    })
    @GetMapping("/me")
    public ResponseEntity<UserInfo> getCurrentUser(
            @AuthenticationPrincipal CustomUserDetails userDetails) {
        UserInfo userInfo = authService.getCurrentUser(userDetails.getUser().getId());
        return ResponseEntity.ok(userInfo);
    }
}
